server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:db-email
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    addresses: amqps://lfbwagwa:Gy6IB-v_BhGnDfCW20_nxQg1GTzOPBZi@beaver.rmq.cloudamqp.com/lfbwagwa
  mail:
    host: smtp.gmail.com
    port: 587
    username: wscarrijojp@gmail.com
    password: "evhq yxyx rako qtua"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# nome para a fila
broker:
  queue:
    email:
      name: default.email
