server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:db-user
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    addresses: amqps://********:Gy6IB-v_BhGnDfCW20_nxQg1GTzOPBZi@beaver.rmq.cloudamqp.com/********
# nome para chave da rota no broker
broker:
  queue:
    email:
      name: default.email
